interactions:
- request:
    body: ''
    headers:
      X-API-KEY:
      - REDACTED
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      host:
      - beta-api.uspto.gov
      user-agent:
      - Mozilla/5.0 Python Patent Clientbot/5.0.4 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://beta-api.uspto.gov/api/v1/patent/applications/15123456/application-data
  response:
    content: '{"count":1,"patentBag":[{"firstInventorToFileIndicator":"Y","filingDate":"2016-09-02","inventorBag":[{"firstName":"Marvin","lastName":"Wang","inventorNameText":"Marvin
      Wang","correspondenceAddressBag":[{"cityName":"Boston","geographicRegionName":"MASSACHUSETTS","geographicRegionCode":"MA","countryCode":"US","nameLineOneText":"Marvin  Wang","countryName":"UNITED
      STATES","postalAddressCategory":"residence"},{"cityName":"Boston","geographicRegionName":"MASSACHUSETTS","geographicRegionCode":"MA","countryCode":"US","postalCode":"02114","nameLineOneText":"Marvin  Wang","countryName":"UNITED
      STATES","addressLineOneText":"Founders 442","postalAddressCategory":"postal"}]}],"applicationStatusDescriptionText":"Abandoned  --  Failure
      to Respond to an Office Action","businessEntityStatusCategory":"Small","firstApplicantName":"The
      General Hospital Corporation","customerNumber":26161,"groupArtUnitNumber":"3775","applicationNumberText":"15123456","earliestPublicationNumber":"US
      2017-0071586 A1","inventionTitle":"TONGUE RETRACTORS FOR FRENOTOMIES","correspondenceAddressBag":[{"cityName":"MINNEAPOLIS","geographicRegionName":"MINNESOTA","geographicRegionCode":"MN","countryCode":"US","postalCode":"55440-1022","nameLineOneText":"FISH
      & RICHARDSON P.C. (BO)","countryName":"UNITED STATES","addressLineOneText":"P.O.
      BOX 1022"}],"firstInventorName":"Marvin Wang","cpcClassificationBag":["A61B13/00","A61B2017/320052","A61B17/02","A61B2017/00814","A61B17/24","A61B17/244"],"applicationConfirmationNumber":7229,"earliestPublicationDate":"2017-03-16","applicationTypeLabelName":"Utility","publicationCategoryBag":["Pre-Grant
      Publications - PGPub"],"applicationStatusDate":"2018-10-02","docketNumber":"29539-0122US1"}],"requestIdentifier":"5f5bb632-f314-4daf-a12c-8c696ab230d1"}'
    headers:
      access-control-allow-headers:
      - Origin, X-Requested-With, Content-Type, Accept
      access-control-allow-methods:
      - OPTIONS,POST,GET
      access-control-allow-origin:
      - '*'
      content-length:
      - '1771'
      content-type:
      - application/json
      date:
      - Fri, 03 May 2024 17:31:32 GMT
      x-amz-apigw-id:
      - XNHaTEB1IAMFdBA=
      x-amzn-requestid:
      - 5f5bb632-f314-4daf-a12c-8c696ab230d1
      x-amzn-trace-id:
      - Root=1-66351f74-40f6252f45f5dbd260259bb4;Parent=5223a2b148c797f6;Sampled=0;lineage=33e8fdb8:0
    http_version: HTTP/2
    status_code: 200
version: 1
