interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - python-requests/2.31.0
      X-API-KEY:
      - oygzgndgwifcpqgvdcitnhorcdvpbb
    method: GET
    uri: https://beta-api.uspto.gov/api/v1/patent/applications/15123456/application-data
  response:
    body:
      string: '{"count":1,"patentBag":[{"firstInventorToFileIndicator":"Y","filingDate":"2016-09-02","inventorBag":[{"firstName":"Marvin","lastName":"Wang","inventorNameText":"Marvin
        Wang","correspondenceAddressBag":[{"cityName":"Boston","geographicRegionName":"MASSACHUSETTS","geographicRegionCode":"MA","countryCode":"US","nameLineOneText":"Marvin  Wang","countryName":"UNITED
        STATES","postalAddressCategory":"residence"},{"cityName":"Boston","geographicRegionName":"MASSACHUSETTS","geographicRegionCode":"MA","countryCode":"US","postalCode":"02114","nameLineOneText":"Marvin  Wang","countryName":"UNITED
        STATES","addressLineOneText":"Founders 442","postalAddressCategory":"postal"}]}],"applicationStatusDescriptionText":"Abandoned  --  Failure
        to Respond to an Office Action","businessEntityStatusCategory":"Small","firstApplicantName":"The
        General Hospital Corporation","customerNumber":26161,"groupArtUnitNumber":"3775","applicationNumberText":"15123456","earliestPublicationNumber":"US
        2017-0071586 A1","inventionTitle":"TONGUE RETRACTORS FOR FRENOTOMIES","correspondenceAddressBag":[{"cityName":"MINNEAPOLIS","geographicRegionName":"MINNESOTA","geographicRegionCode":"MN","countryCode":"US","postalCode":"55440-1022","nameLineOneText":"FISH
        & RICHARDSON P.C. (BO)","countryName":"UNITED STATES","addressLineOneText":"P.O.
        BOX 1022"}],"firstInventorName":"Marvin Wang","cpcClassificationBag":["A61B13/00","A61B2017/320052","A61B17/02","A61B2017/00814","A61B17/24","A61B17/244"],"applicationConfirmationNumber":7229,"earliestPublicationDate":"2017-03-16","applicationTypeLabelName":"Utility","publicationCategoryBag":["Pre-Grant
        Publications - PGPub"],"applicationStatusDate":"2018-10-02","docketNumber":"29539-0122US1"}],"requestIdentifier":"e83001fa-56f7-4b08-a316-4b0417592967"}'
    headers:
      Connection:
      - keep-alive
      Content-Length:
      - '1771'
      Content-Type:
      - application/json
      Date:
      - Wed, 10 Apr 2024 20:43:11 GMT
      X-Amzn-Trace-Id:
      - Root=1-6616f9df-191832f77f8b29a1618d3d83;Parent=07b4e1776e6bec25;Sampled=0;lineage=33e8fdb8:0
      access-control-allow-headers:
      - Origin, X-Requested-With, Content-Type, Accept
      access-control-allow-methods:
      - OPTIONS,POST,GET
      access-control-allow-origin:
      - '*'
      x-amz-apigw-id:
      - WBv69HwFoAMF6mg=
      x-amzn-RequestId:
      - e83001fa-56f7-4b08-a316-4b0417592967
    status:
      code: 200
      message: OK
version: 1
