interactions:
- request:
    body: ''
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      host:
      - beta-api.uspto.gov
      user-agent:
      - Mozilla/5.0 Python Patent Clientbot/4.1.10 (parkerhancock@users.noreply.github.com)
      x-api-key:
      - oygzgndgwifcpqgvdcitnhorcdvpbb
    method: GET
    uri: https://beta-api.uspto.gov/api/v1/patent/applications/15123456/assignment
  response:
    content: '{"count":1,"patentBag":[{"assignmentBag":[{"assignmentReceivedDate":"2018-10-25","assignorBag":[{"executionDate":"2018-09-23","assignorName":"WANG,
      MARVIN "}],"frameNumber":"0442","pageNumber":4,"reelNumber/frameNumber":"047305/0442","assignmentRecordedDate":"2018-10-25","conveyanceText":"ASSIGNMENT
      OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).","assigneeBag":[{"assigneeAddress":{"cityName":"BOSTON","geographicRegionCode":"MA
      ","postalCode":"02114","addressLineOneText":"55 FRUIT STREET"},"assigneeNameText":"THE
      GENERAL HOSPITAL CORPORATION"}],"assignmentMailedDate":"2018-10-26","reelNumber":"047305","correspondenceAddress":[{"addressLineThreeText":"MINNEAPOLIS,
      MN 55440-1022","addressLineOneText":"FISH & RICHARDSON P.C.","correspondentNameText":"J.
      P. FASSE","addressLineTwoText":"P.O.BOX 1022"}]}]}],"requestIdentifier":"cead61ac-1743-47c2-a561-cd30caa835f0"}'
    headers:
      access-control-allow-headers:
      - Origin, X-Requested-With, Content-Type, Accept
      access-control-allow-methods:
      - OPTIONS,POST,GET
      access-control-allow-origin:
      - '*'
      content-length:
      - '874'
      content-type:
      - application/json
      date:
      - Thu, 25 Apr 2024 16:50:11 GMT
      x-amz-apigw-id:
      - Wyp2mEiioAMFeww=
      x-amzn-requestid:
      - cead61ac-1743-47c2-a561-cd30caa835f0
      x-amzn-trace-id:
      - Root=1-662a89c3-19af58174e2bd0d626303c3e;Parent=6bd48688e4a7905a;Sampled=0;lineage=33e8fdb8:0
    http_version: HTTP/2
    status_code: 200
- request:
    body: ''
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      host:
      - beta-api.uspto.gov
      user-agent:
      - Mozilla/5.0 Python Patent Clientbot/4.1.10 (parkerhancock@users.noreply.github.com)
      x-api-key:
      - oygzgndgwifcpqgvdcitnhorcdvpbb
    method: GET
    uri: https://beta-api.uspto.gov/api/v1/patent/applications/15123456/transactions
  response:
    content: '{"count":1,"patentBag":[{"transactionContentBag":[{"recordedDate":"2016-09-02","caseActionDescriptionText":"Initial
      Exam Team nn","caseActionCode":"IEXX"},{"recordedDate":"2016-09-02","caseActionDescriptionText":"Entity
      Status Set To Undiscounted (Initial Default Setting or Status Change)","caseActionCode":"BIG."},{"recordedDate":"2016-09-02","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"WIDS"},{"recordedDate":"2016-12-01","caseActionDescriptionText":"Applicant
      Has Filed a Verified Statement of Small Entity Status in Compliance with 37
      CFR 1.27","caseActionCode":"SMAL"},{"recordedDate":"2016-09-02","caseActionDescriptionText":"Applicants
      have given acceptable permission for participating foreign","caseActionCode":"APPERMS"},{"recordedDate":"2016-12-07","caseActionDescriptionText":"Email
      Notification","caseActionCode":"EML_NTR"},{"recordedDate":"2016-12-07","caseActionDescriptionText":"Email
      Notification","caseActionCode":"EML_NTR"},{"recordedDate":"2016-12-07","caseActionDescriptionText":"Filing
      Receipt","caseActionCode":"FLRCPT.O"},{"recordedDate":"2016-12-07","caseActionDescriptionText":"Notice
      of DO/EO Acceptance Mailed","caseActionCode":"M903"},{"recordedDate":"2016-09-02","caseActionDescriptionText":"Patent
      Term Adjustment - Ready for Examination","caseActionCode":"PTA.RFE"},{"recordedDate":"2016-12-06","caseActionDescriptionText":"FITF
      set to YES - revise initial setting","caseActionCode":"FTFS"},{"recordedDate":"2016-12-06","caseActionDescriptionText":"Sent
      to Classification Contractor","caseActionCode":"PGPC"},{"recordedDate":"2016-10-23","caseActionDescriptionText":"371
      Completion Date","caseActionCode":"371COMP"},{"recordedDate":"2017-01-04","caseActionDescriptionText":"Case
      Docketed to Examiner in GAU","caseActionCode":"DOCK"},{"recordedDate":"2017-01-06","caseActionDescriptionText":"Email
      Notification","caseActionCode":"EML_NTR"},{"recordedDate":"2017-01-05","caseActionDescriptionText":"Change
      in Power of Attorney (May Include Associate POA)","caseActionCode":"PA.."},{"recordedDate":"2017-01-03","caseActionDescriptionText":"Application
      Dispatched from OIPE","caseActionCode":"OIPE"},{"recordedDate":"2017-01-03","caseActionDescriptionText":"Application
      Is Now Complete","caseActionCode":"COMP"},{"recordedDate":"2017-03-17","caseActionDescriptionText":"Email
      Notification","caseActionCode":"EML_NTR"},{"recordedDate":"2017-03-16","caseActionDescriptionText":"Application
      ready for PDX access by participating foreign offices","caseActionCode":"CCRDY"},{"recordedDate":"2017-03-16","caseActionDescriptionText":"PG-Pub
      Issue Notification","caseActionCode":"PG-ISSUE"},{"recordedDate":"2017-06-19","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"WIDS"},{"recordedDate":"2017-06-19","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"WIDS"},{"recordedDate":"2016-09-02","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"M844"},{"recordedDate":"2016-09-02","caseActionDescriptionText":"Preliminary
      Amendment","caseActionCode":"A.PE"},{"recordedDate":"2016-09-02","caseActionDescriptionText":"Request
      for Foreign Priority (Priority Papers May Be Included)","caseActionCode":"RQPR"},{"recordedDate":"2017-06-19","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"M844"},{"recordedDate":"2017-11-08","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"WIDS"},{"recordedDate":"2017-11-08","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"M844"},{"recordedDate":"2017-11-08","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"WIDS"},{"recordedDate":"2017-11-08","caseActionDescriptionText":"Information
      Disclosure Statement (IDS) Filed","caseActionCode":"M844"},{"recordedDate":"2018-02-20","caseActionDescriptionText":"Case
      Docketed to Examiner in GAU","caseActionCode":"DOCK"},{"recordedDate":"2018-02-28","caseActionDescriptionText":"Information
      Disclosure Statement considered","caseActionCode":"IDSC"},{"recordedDate":"2018-02-28","caseActionDescriptionText":"Information
      Disclosure Statement considered","caseActionCode":"IDSC"},{"recordedDate":"2018-02-28","caseActionDescriptionText":"Non-Final
      Rejection","caseActionCode":"CTNF"},{"recordedDate":"2018-02-28","caseActionDescriptionText":"Information
      Disclosure Statement considered","caseActionCode":"IDSC"},{"recordedDate":"2018-03-14","caseActionDescriptionText":"Email
      Notification","caseActionCode":"EML_NTF"},{"recordedDate":"2018-03-14","caseActionDescriptionText":"Electronic
      Review","caseActionCode":"ELC_RVW"},{"recordedDate":"2018-03-14","caseActionDescriptionText":"Mail
      Non-Final Rejection","caseActionCode":"MCTNF"},{"recordedDate":"2018-10-10","caseActionDescriptionText":"Email
      Notification","caseActionCode":"EML_NTR"},{"recordedDate":"2018-10-10","caseActionDescriptionText":"Mail
      Abandonment for Failure to Respond to Office Action","caseActionCode":"MABN2"},{"recordedDate":"2018-10-02","caseActionDescriptionText":"Aband.
      for Failure to Respond to O. A.","caseActionCode":"ABN2"},{"recordedDate":"2020-07-27","caseActionDescriptionText":"Petition
      Decision - Granted","caseActionCode":"PTGR"},{"recordedDate":"2020-07-28","caseActionDescriptionText":"Mail-Petition
      Decision - Granted","caseActionCode":"MPTGR"},{"recordedDate":"2020-07-01","caseActionDescriptionText":"Petition
      Entered","caseActionCode":"PET."},{"recordedDate":"2020-10-21","caseActionDescriptionText":"Information
      Disclosure Statement considered","caseActionCode":"IDSC"}]}],"requestIdentifier":"3ee6b6ce-4bed-4e27-bded-368c8368dfcd"}'
    headers:
      access-control-allow-headers:
      - Origin, X-Requested-With, Content-Type, Accept
      access-control-allow-methods:
      - OPTIONS,POST,GET
      access-control-allow-origin:
      - '*'
      content-length:
      - '5764'
      content-type:
      - application/json
      date:
      - Thu, 25 Apr 2024 16:50:11 GMT
      x-amz-apigw-id:
      - Wyp2oGENoAMF0VQ=
      x-amzn-requestid:
      - 3ee6b6ce-4bed-4e27-bded-368c8368dfcd
      x-amzn-trace-id:
      - Root=1-662a89c3-141d37d929496fd855281e3e;Parent=466a0a28232918fa;Sampled=0;lineage=33e8fdb8:0
    http_version: HTTP/2
    status_code: 200
version: 1
