repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: unasync
        name: unasync
        entry: python unasync.py
        language: system
        always_run: true
        require_serial: true

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.2
  hooks:
  # Run the linter
  - id: ruff
    args: [ --fix ]
  # Run the formatter
  - id: ruff-format
-   repo: meta
    hooks:
    -   id: check-hooks-apply
- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)