interactions:
- request:
    body: ''
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      host:
      - developer.uspto.gov
      user-agent:
      - Mozilla/5.0 Python Patent Clientbot/3.2.10 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://developer.uspto.gov/ptab-api/proceedings?applicationNumberText=09089931
  response:
    content: "{\"aggregationData\":{},\"results\":[{\"institutionDecisionDate\":\"09-28-2016\",\"proceedingFilingDate\":\"04-01-2016\",\"accordedFilingDate\":\"04-01-2016\",\"proceedingStatusCategory\":\"Terminated-Settled\",\"proceedingNumber\":\"IPR2016-00833\",\"proceedingLastModifiedDate\":\"07-06-2017\",\"proceedingTypeCategory\":\"AIA
      Trial\",\"subproceedingTypeCategory\":\"IPR\",\"respondentTechnologyCenterNumber\":\"2800\",\"respondentPatentOwnerName\":\"Silicon
      Genesis Corporation\",\"respondentPartyName\":\"Silicon Genesis Corporation\",\"respondentInventorName\":\"FRANCOIS
      HENLEY\",\"respondentCounselName\":\"Margaux Nair\",\"respondentGrantDate\":\"08-15-2000\",\"respondentPatentNumber\":\"6103599\",\"respondentApplicationNumberText\":\"09089931\",\"petitionerPartyName\":\"Commissariat
      a l\u2019Energie Atomique et aux Energies Alternatives\",\"petitionerCounselName\":\"Paul
      McGowan\",\"decisionDate\":\"07-06-2017\",\"additionalRespondentPartyDataBag\":[]}],\"recordTotalQuantity\":1}"
    headers:
      access-control-allow-credentials:
      - 'true'
      access-control-allow-headers:
      - accept, authorization, content-type, x-requested-with
      access-control-allow-methods:
      - GET, POST, OPTIONS, PUT
      access-control-allow-origin:
      - '*'
      access-control-max-age:
      - '1'
      content-type:
      - application/json
      date:
      - Fri, 03 Nov 2023 18:39:00 GMT
      strict-transport-security:
      - max-age=31536000;
      vary:
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    http_version: HTTP/2
    status_code: 200
- request:
    body: ''
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      host:
      - developer.uspto.gov
      user-agent:
      - Mozilla/5.0 Python Patent Clientbot/3.2.10 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://developer.uspto.gov/ptab-api/proceedings?applicationNumberText=09089931&recordStartNumber=0&recordTotalQuantity=25&sortOrderCategory=
  response:
    content: "{\"aggregationData\":{},\"results\":[{\"institutionDecisionDate\":\"09-28-2016\",\"proceedingFilingDate\":\"04-01-2016\",\"accordedFilingDate\":\"04-01-2016\",\"proceedingStatusCategory\":\"Terminated-Settled\",\"proceedingNumber\":\"IPR2016-00833\",\"proceedingLastModifiedDate\":\"07-06-2017\",\"proceedingTypeCategory\":\"AIA
      Trial\",\"subproceedingTypeCategory\":\"IPR\",\"respondentTechnologyCenterNumber\":\"2800\",\"respondentPatentOwnerName\":\"Silicon
      Genesis Corporation\",\"respondentPartyName\":\"Silicon Genesis Corporation\",\"respondentInventorName\":\"FRANCOIS
      HENLEY\",\"respondentCounselName\":\"Margaux Nair\",\"respondentGrantDate\":\"08-15-2000\",\"respondentPatentNumber\":\"6103599\",\"respondentApplicationNumberText\":\"09089931\",\"petitionerPartyName\":\"Commissariat
      a l\u2019Energie Atomique et aux Energies Alternatives\",\"petitionerCounselName\":\"Paul
      McGowan\",\"decisionDate\":\"07-06-2017\",\"additionalRespondentPartyDataBag\":[]}],\"recordTotalQuantity\":1}"
    headers:
      access-control-allow-credentials:
      - 'true'
      access-control-allow-headers:
      - accept, authorization, content-type, x-requested-with
      access-control-allow-methods:
      - GET, POST, OPTIONS, PUT
      access-control-allow-origin:
      - '*'
      access-control-max-age:
      - '1'
      content-type:
      - application/json
      date:
      - Fri, 03 Nov 2023 18:39:00 GMT
      strict-transport-security:
      - max-age=31536000;
      vary:
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    http_version: HTTP/2
    status_code: 200
- request:
    body: ''
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      host:
      - developer.uspto.gov
      user-agent:
      - Mozilla/5.0 Python Patent Clientbot/3.2.10 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://developer.uspto.gov/ptab-api/proceedings?applicationNumberText=09089931&recordStartNumber=0&recordTotalQuantity=1&sortOrderCategory=
  response:
    content: "{\"aggregationData\":{},\"results\":[{\"institutionDecisionDate\":\"09-28-2016\",\"proceedingFilingDate\":\"04-01-2016\",\"accordedFilingDate\":\"04-01-2016\",\"proceedingStatusCategory\":\"Terminated-Settled\",\"proceedingNumber\":\"IPR2016-00833\",\"proceedingLastModifiedDate\":\"07-06-2017\",\"proceedingTypeCategory\":\"AIA
      Trial\",\"subproceedingTypeCategory\":\"IPR\",\"respondentTechnologyCenterNumber\":\"2800\",\"respondentPatentOwnerName\":\"Silicon
      Genesis Corporation\",\"respondentPartyName\":\"Silicon Genesis Corporation\",\"respondentInventorName\":\"FRANCOIS
      HENLEY\",\"respondentCounselName\":\"Margaux Nair\",\"respondentGrantDate\":\"08-15-2000\",\"respondentPatentNumber\":\"6103599\",\"respondentApplicationNumberText\":\"09089931\",\"petitionerPartyName\":\"Commissariat
      a l\u2019Energie Atomique et aux Energies Alternatives\",\"petitionerCounselName\":\"Paul
      McGowan\",\"decisionDate\":\"07-06-2017\",\"additionalRespondentPartyDataBag\":[]}],\"recordTotalQuantity\":1}"
    headers:
      access-control-allow-credentials:
      - 'true'
      access-control-allow-headers:
      - accept, authorization, content-type, x-requested-with
      access-control-allow-methods:
      - GET, POST, OPTIONS, PUT
      access-control-allow-origin:
      - '*'
      access-control-max-age:
      - '1'
      content-type:
      - application/json
      date:
      - Thu, 09 Nov 2023 16:18:04 GMT
      strict-transport-security:
      - max-age=31536000;
      vary:
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    http_version: HTTP/2
    status_code: 200
version: 1
