interactions:
- request:
    body: '{"caseId": 27915804, "hl_snippets": "2", "op": "OR", "q": "\"20160009839\".PN.",
      "queryName": "\"20160009839\".PN.", "highlights": "1", "qt": "brs", "spellCheck":
      false, "viewName": "tile", "plurals": true, "britishEquivalents": true, "databaseFilters":
      [{"databaseName": "US-PGPUB", "countryCodes": []}], "searchType": 1, "ignorePersist":
      true, "userEnteredQuery": "\"20160009839\".PN."}'
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-length:
      - '388'
      content-type:
      - application/json
      host:
      - ppubs.uspto.gov
      user-agent:
      - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/114.0.0.0 Safari/537.36
      x-access-token:
      - eyJzdWIiOiJiZTU0YjA0ZC1mZGYxLTQ5NGMtYjUyZS00M2Q4ZWRiZjk1MDgiLCJ2ZXIiOiIxYTg3NmI0Ny0yM2NlLTQ2ZGItOWViNy1mNmRhODY3OTZjZmMiLCJleHAiOjB9
      x-requested-with:
      - XMLHttpRequest
    method: POST
    uri: https://ppubs.uspto.gov/dirsearch-public/searches/counts
  response:
    content: '{ "message": "Too many requests" }'
    headers:
      content-length:
      - '34'
      content-type:
      - application/json;charset=ISO-8859-1
      date:
      - Wed, 24 Apr 2024 17:32:27 GMT
      server-timing:
      - intid;desc=f2d54e3b6441d109
      x-rate-limit-retry-after-seconds:
      - '0'
    http_version: HTTP/2
    status_code: 429
- request:
    body: '{"caseId": 27915804, "hl_snippets": "2", "op": "OR", "q": "\"20160009839\".PN.",
      "queryName": "\"20160009839\".PN.", "highlights": "1", "qt": "brs", "spellCheck":
      false, "viewName": "tile", "plurals": true, "britishEquivalents": true, "databaseFilters":
      [{"databaseName": "US-PGPUB", "countryCodes": []}], "searchType": 1, "ignorePersist":
      true, "userEnteredQuery": "\"20160009839\".PN."}'
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-length:
      - '388'
      content-type:
      - application/json
      host:
      - ppubs.uspto.gov
      user-agent:
      - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/114.0.0.0 Safari/537.36
      x-access-token:
      - eyJzdWIiOiJiZTU0YjA0ZC1mZGYxLTQ5NGMtYjUyZS00M2Q4ZWRiZjk1MDgiLCJ2ZXIiOiIxYTg3NmI0Ny0yM2NlLTQ2ZGItOWViNy1mNmRhODY3OTZjZmMiLCJleHAiOjB9
      x-requested-with:
      - XMLHttpRequest
    method: POST
    uri: https://ppubs.uspto.gov/dirsearch-public/searches/counts
  response:
    content: '{ "message": "Too many requests" }'
    headers:
      content-length:
      - '34'
      content-type:
      - application/json;charset=ISO-8859-1
      date:
      - Wed, 24 Apr 2024 17:32:27 GMT
      server-timing:
      - intid;desc=59d9d41937b025f9
      x-rate-limit-retry-after-seconds:
      - '0'
    http_version: HTTP/2
    status_code: 429
version: 1
